version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: faraday-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: haslo123 
      POSTGRES_DB: db
    volumes:
      - faraday_pg_data:/var/lib/postgresql/data

volumes:
  faraday_pg_data: